### ISSUE TITLE
Mutating Arrays and Objects throws errors with vue transitions

### ISSUE THREAD

**Issue by exophunk** [BosNaufal/vue-freeze#2]
What is the best way to mutate an array or an object in the state? I can only replace the whole array or object right?

**This works:**

``` javascript
store.on('ui:disableStep', (index, oldStore) => {
    let steps = oldStore.ui.steps;
    steps[index].isVisible = false;
    store.get().ui.set({ steps: steps });
});
```

**This doesn't work:** (obviously)

``` javascript
store.on('ui:disableStep', (index, oldStore) => {
    store.get().ui.steps[index].isVisible = false;
});
```

I get strange bugs with vue.js transitions (I have a transition on a "step" when it gets removed)

``` html
<step v-for="step in state.ui.steps" v-show="step.isVisible" transition="remove"></step>
```

The error: 

> app.js:25010 Uncaught TypeError: this.op is not a function

It's related to the transition process and thrown in the `leaveDone()` function.

When I use my array of steps inside the components `data()` it all works fine. It seems that the "v-for" or "v-show" has troubles with getting the whole array replaced every time. How can we handle that with a vue-freeze store?

**Comment by BosNaufal** [comment]
Hello @exophunk, Sorry for slow respond But Thank you for using Vue Freeze~ :grin: 

The best practice to mutate an Array or Object you can do like [Freezer Documentation](https://github.com/arqex/freezer#set-keyorobject-value-) says. like,

``` javascript
var freezer = new Freezer({obj: {a:'hola', b:'adios'}, arr: [1,2]});

// Updating using a hash
freezer.get().obj.set( {b:'bye', c:'ciao'} );

// Updating using key and value
freezer.get().arr.set( 0, 0 );

// {obj: {a:'hola', b:'bye', c:'ciao'}, arr: [0,2]}
console.log( freezer.get() )
```

If you've found the answer for your problem please close this issue :smile: 

Last but not least, Thank you for sending me an issue~ :smile:

**Comment by exophunk** [comment]
Thank you for your help!
